# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Play Quiz-, Mini- and Brain-Games against your Friends.
email: contact@kazong-games.com
description: > # this means to ignore newlines until "baseurl:"
  Kazong Game | Quiz, Mini, Brain-Game Multiplayer APP
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kazong-game.com" # the base hostname & protocol for your site
twitter_username: kazong_game
languages:
  - de
  - en
  - fr
  - it
  - es
default_language: de

# Build settings
markdown: kramdown
sass:
    style: compressed
